# Generated by Django 4.2 on 2023-04-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
